version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./target/MyBackend-0.0.1-SNAPSHOT.jar:/app/app.jar
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/dev
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Root@1234
    networks:
      - my_shared_network

networks:
  my_shared_network:
    external: true