spring:
  profiles:
    active: ${PROFILE:prod}
  application:
    name: MyBackend

  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: false
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  liquibase:
    enabled: true
    change-log: classpath:/db/db.changelog-master.xml

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            redirect-uri: ${GITHUB_REDIRECT_URI}
            scope:
              - user:email
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: login

  mail:
    host: smtp.gmail.com
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
        mail:
          smtp:
            connectiontimeout: 5000
            timeout: 5000
            writetimeout: 5000
            auth: true
            starttls:
              enable: true

logging:
  level:
    org:
      hibernate:
        orm.connections.pooling: off
        orm.deprecation: off
        hibernate: error

app:
  logging_features:
    print_db_info: true
    print_app_summary: true
  environment: ${APP_ENVIRONMENT:local}
  frontendUrl: ${APP_FRONTEND_URL:http://localhost:5173/dinemaster-ui}
  resend:
    api: ${RESEND_API}

langchain4j:
  ollama:
    chat-model:
      base-url: ${OLLAMA_BASE_URL:http://localhost:11434}
      model-name: ${OLLAMA_MODEL:gemma4}
      timeout: PT5M

server:
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: ${KEYSTORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: mycert