package com.backend.MyBackend.notification.enums;

public enum NotificationActionType {
    NONE,VERIFY_EMAIL,OPEN_PROFILE,CHANGE_PASSWORD,VIEW_ORDER,VIEW_RESTAURANT,OPEN_CART,COMPLETE_PROFILE,OPEN_SETTINGS,CONTACT_SUPPORT,OPEN_URL,RETRY_PAYMENT
}
