name: Deploy to HomeLab

on:
  push:
    branches:
      - preprod

jobs:
  deploy:
    runs-on: self-hosted
    environment: PREPROD_ENV_FILE

    steps:
      - uses: actions/checkout@v4

      - name: Create secrets.env
        run: |
          cd /home/revanthdev/src/MyBackend
          cat > secrets.env <<EOF
          SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }}
          SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }}
          SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }}
          SMTP_USERNAME=${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}
          RESEND_API=${{ secrets.RESEND_API }}
          KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}
          PROFILE=${{ secrets.PROFILE }}
          OLLAMA_BASE_URL=${{ secrets.OLLAMA_BASE_URL }}
          APP_ENVIRONMENT=${{ secrets.APP_ENVIRONMENT }}
          EOF
          chmod 600 secrets.env

      - name: Build Spring Boot
        run: |
          cd /home/revanthdev/src/MyBackend
          mvn clean install -DskipTests

      - name: Deploy
        run: |
          cd /home/revanthdev/src/MyBackend
          git fetch origin
          git checkout preprod
          git reset --hard origin/preprod

          docker compose down
          docker compose build --no-cache
          docker compose up -d

          docker image prune -f