name: Deploy PreProd

on:
  push:
    branches:
      - preprod

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Deploy
        run: |
          cd /home/revanthdev/src/MyBackend
          git fetch origin
          git checkout preprod
          git reset --hard origin/preprod

          docker compose down
          docker compose up --build -d

          docker image prune -f